version: '3.1'

services:
  flink-jobmanager:
    image: flink:scala_2.12-java8
    hostname: "flink-jobmanager"
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager

  flink-taskmanager:
    image: flink:scala_2.12-java8
    hostname: "flink-taskmanager"
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    deploy:
      replicas: 1
